server:
  port: 8080
spring:
  application:
    name: "arquitectura-hexagonal"
  devtools:
    add-properties: false

  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://FrankOrtegon:sofka1234@sofka.3mcv4.mongodb.net/user?retryWrites=true&w=majority"

